create table operation (
    id integer generated by default as identity,
    description varchar(30) not null,

    primary key (id)
);

insert into
    operation
(description)
values
    ('COMPRA A VISTA'),
    ('COMPRA PARCELADA'),
    ('SAQUE'),
    ('PAGAMENTO');